# Generated by Django 3.1.7 on 2021-05-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=150)),
                ('descripcion_actividad', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_realizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('codigo_agencia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_agencia', models.CharField(max_length=250)),
                ('direccion_agencia', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id_comite', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comite', models.CharField(max_length=150, unique=True)),
                ('descripcion_comite', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaCliente',
            fields=[
                ('id_encuestaCliente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pregunta', models.CharField(max_length=300)),
                ('titulo_encuesta_cliente', models.CharField(max_length=250)),
                ('visibilidad_pregunta_cliente', models.CharField(default='S', max_length=1)),
                ('codigo_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaPersonal',
            fields=[
                ('id_encuestaPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pregunta', models.CharField(max_length=300)),
                ('titulo_encuesta_personal', models.CharField(max_length=250)),
                ('visibilidad_pregunta_personal', models.CharField(default='S', max_length=1)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuestaPersonal',
            fields=[
                ('id_respuesta_encuesta_personal', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_personal', models.IntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.encuestapersonal')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuestaCliente',
            fields=[
                ('id_respuesta_encuesta_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_cliente', models.IntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.encuestacliente')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.agencia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.departamento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_comite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.comite'),
        ),
    ]
