# Generated by Django 3.1.1 on 2021-06-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210504_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('codigo_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.agencia')),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.departamento')),
                ('id_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.comite')),
            ],
        ),
    ]
