# Generated by Django 3.1.7 on 2021-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacliente',
            name='fecha_desde_cliente',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestacliente',
            name='fecha_hasta_cliente',
            field=models.DateField(blank=True, null=True),
        ),
    ]
