# Generated by Django 3.1.7 on 2021-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20210725_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestapersonal',
            name='fecha_desde_personal',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestapersonal',
            name='fecha_hasta_personal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
