# Generated by Django 3.1.7 on 2021-06-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210524_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=1, max_length=200, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=4, max_length=200, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador')], default='ADM', max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
